apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-namespace
  labels:
    app: kafka
spec:
  clusterIP: None    # Headless service
  ports:
    - name: kafka
      port: 9092
  selector:
    app: kafka
